language: java

jdk:
  - openjdk7

install: true

addons:
  hosts:
    - localhost

script:
    - mvn clean test jacoco:report coveralls:report

after_success:
  - mvn clean test jacoco:report coveralls:report