language: java

jdk:
  - openjdk7

install: true

addons:
  hosts:
    - localhost

script:
    - npm install express
    - node fakeExpressController
    - sleep 2
    
after_success:
  - mvn clean test jacoco:report coveralls:report